channels:
  - defaults
  - conda-forge
dependencies:
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - datashape
  - appmode
  - ipynb-py-convert
  - ipywidgets
  - matplotlib=3.3.4
  - numpy=1.19.2
  - pandas=1.0.2
  - scipy=1.5.2
  - seaborn=0.11.1
#  - jupytext
#  - python-kaleido
#  - seaborn
#  - ipython
#  - ipython=8.5.0
#  - ipywidgets=7.5.1
#  - voila
#  - proj4
#  - basemap
#  - mpld3
#  - plotly
#  - dash-core-components
#  - dash
#  - dash-html-components
#  - cartopy
#  - shapely
#  - imutils
#  - opencv
#  - python
