channels:
  - defaults
  - conda-forge
dependencies:
  - anaconda
  - conda
  - conda-build
  - _ipyw_jlab_nb_ext_conf
  - anaconda-navigator
  - navigator-updater
  - python
  - datashape
  - pandas
  - jupyterlab
  - ipywidgets
  - nodejs
  - appmode
  - jupyter
  - voila
  - proj4
  - basemap
  - mpld3
  - plotly
  - dash-core-components
  - dash
  - dash-html-components
  - cartopy
  - shapely
  - imutils
  - opencv
  - ipynb-py-convert
  - jupytext
  - python-kaleido
