channels:
  - defaults
  - conda-forge
dependencies:
  - _ipyw_jlab_nb_ext_conf
  - python
  - datashape
  - pandas
#  - ipywidgets
  - appmode
  - voila
#  - proj4
#  - basemap
  - mpld3
  - plotly
  - dash-core-components
  - dash
  - dash-html-components
 # - cartopy
  - shapely
  - imutils
  - opencv
  - ipynb-py-convert
  - jupytext
  - python-kaleido
