channels:
  - defaults
  - conda-forge
dependencies:
  - nodejs
  - python
  - anaconda
  - datashape
  - appmode
  - ipynb-py-convert
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
#  - jupytext
#  - python-kaleido
#  - seaborn
#  - ipython
#  - ipython=8.5.0
#  - ipywidgets=7.5.1
#  - voila
#  - proj4
#  - basemap
#  - mpld3
#  - plotly
#  - dash-core-components
#  - dash
#  - dash-html-components
#  - cartopy
#  - shapely
#  - imutils
#  - opencv
#  - python
#  - _ipyw_jlab_nb_ext_conf
